version: "3.9"
volumes:
  mongodata:
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: data
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret
  dbseed:
    build: ./dbseed
    depends_on:
      - mongo
  neo4j:
      image: neo4j:4.4.0-community
      container_name: neo4j
      ports:
          - "7474:7474"   #HTTP
          - "7473:7473"   #HTTPS
          - "7687:7687"   #Bolt
      environment:
          - NEO4J_AUTH=neo4j/SuperSecret
          - NEO4JLABS_PLUGINS=["graph-data-science"]
  risk-engine:
    build: risk/
    container_name: risk-engine
    depends_on:
      - mongo
    ports:
      - "5001:5001"
  tilt-engine:
    build: tilt/
    container_name: tilt-engine
    depends_on:
      - mongo
    ports:
      - "7001:7001"
  analysis-engine:
    build: analysis/
    container_name: analysis-engine
    depends_on:
      - mongo
      - dbseed
      - neo4j
      - risk-engine
      - tilt-engine
    ports:
      - "8000:8000"
